# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e6f97f1d5dfb7d1561b1709659e8bc701044be3d4da8469ce22b28fd117a188e017d8d285147e3b0eeb993d088939769fe1d935a8464122655c5795c4fc24293

test:
  secret_key_base: f7f2dc41ea02b796cd9c997d330e22199f06172b391fa825692b5e3d5a321d1638ed8bdd95649b51b5891ed5d85d339e5cb1510de0c0c3dba3cceb12f47f1563

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
